# Generated by Django 4.2.3 on 2023-07-27 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booms',
            fields=[
                ('pn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=125)),
                ('commodity', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=30)),
                ('ubiLogic', models.CharField(max_length=15)),
                ('project', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('employee_e', models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pn_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.booms')),
            ],
        ),
        migrations.CreateModel(
            name='Failures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureDate', models.DateTimeField(auto_now=True)),
                ('analysis', models.CharField(max_length=100)),
                ('rootCause', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('defectSymptom', models.CharField(max_length=100)),
                ('shiftFailure', models.CharField(max_length=13)),
                ('correctiveActions', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('employee_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_er', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.errormessages')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('pn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationProject', models.CharField(max_length=100)),
                ('stationName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uut',
            fields=[
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('employee_e', models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pn_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.booms')),
            ],
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRejected', models.DateTimeField(auto_now=True)),
                ('snDamaged', models.CharField(max_length=50)),
                ('snNew', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=15)),
                ('employee_e', models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.failures')),
                ('pn_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.booms')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceType', models.CharField(max_length=100)),
                ('failureM', models.CharField(max_length=100)),
                ('causeCategoryS', models.CharField(max_length=100)),
                ('dateStart', models.DateTimeField(auto_now=True)),
                ('dateFinish', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('employee_e', models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_sp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.sparepart')),
                ('statition_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.station')),
            ],
        ),
        migrations.AddField(
            model_name='failures',
            name='id_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.station'),
        ),
        migrations.AddField(
            model_name='failures',
            name='sn_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.uut'),
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('pmd', models.BooleanField(default=False)),
                ('dell', models.BooleanField(default=False)),
                ('switch', models.BooleanField(default=False)),
                ('mail', models.CharField(max_length=100, null=True)),
                ('privileges', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('employeeNumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
