# Generated by Django 4.2.3 on 2023-07-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='id',
        ),
        migrations.AlterField(
            model_name='employes',
            name='employeeNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
