# Generated by Django 4.2.3 on 2023-07-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Employes',
        ),
    ]
