# Generated by Django 4.2.3 on 2023-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0002_rename_users_employes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employes',
            name='password',
            field=models.CharField(default='12345', max_length=30),
        ),
    ]
