# Generated by Django 4.2.3 on 2023-07-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0002_remove_employes_id_alter_employes_employeenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='employee_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
    ]
