# Generated by Django 4.2.3 on 2023-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0003_employes_created_employes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employes',
            name='privileges',
            field=models.CharField(max_length=10),
        ),
    ]
