# Generated by Django 4.2.1 on 2023-08-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0003_alter_failures_employee_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessages',
            name='employee_e',
            field=models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='employee_e',
            field=models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='uut',
            name='employee_e',
            field=models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
    ]
