# Generated by Django 4.2.3 on 2023-07-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0004_alter_employes_mail_alter_employes_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uut',
            fields=[
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pn', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.employes')),
            ],
        ),
    ]
