# Generated by Django 5.2.5 on 2025-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0004_employes_qa_alter_failures_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='RowMM',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booms',
            name='product',
            field=models.CharField(choices=[('Senna', 'Senna'), ('Pathfinder', 'Pathfinder'), ('Sojouner', 'Sojouner'), ('Hook', 'Hook'), ('Outlander', 'Outlander'), ('Minerrall Well', 'Minerrall Well'), ('MMCs', 'MCCs'), ('Fornax SAM', 'Fornax SAM'), ('Fornax DIB', 'Fornax DIB'), ('Fornax CIT', 'Fornax CIT'), ('Indus DIB', 'Indus DIB'), ('Indus BOP', 'Indus BOP'), ('Indus SAM', 'Indus SAM'), ('Indus CIT', 'Indus CIT'), ('PMDU', 'PMDU'), ('Switch', 'Switch'), ('Kura', 'Kura'), ('Sled', 'Sled'), ('Rack', 'Rack'), ('Row Manager', 'Row Manager')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booms',
            name='project',
            field=models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW'), ('SONY', 'SONY'), ('RWMM', 'RWMM')], max_length=20),
        ),
    ]
