# Generated by Django 5.2.5 on 2025-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0005_employes_rowmm_alter_booms_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stationProject',
            field=models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW'), ('SONY', 'SONY'), ('ROWM', 'ROWM')], max_length=50),
        ),
    ]
