# Generated by Django 4.2.3 on 2023-07-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0005_uut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uut',
            old_name='employee',
            new_name='employee_e',
        ),
        migrations.CreateModel(
            name='Failures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateTimeField(auto_now=True)),
                ('error_message', models.CharField(max_length=160)),
                ('analysis', models.CharField(max_length=100)),
                ('root_cause', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('defect_symptom', models.CharField(max_length=100)),
                ('shift_failure', models.CharField(max_length=13)),
                ('corrective_actions', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('employee_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.employes')),
                ('sn_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.uut')),
            ],
        ),
    ]
