# Generated by Django 4.2.3 on 2023-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0006_alter_booms_employee_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booms',
            name='product',
            field=models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW')], max_length=30),
        ),
    ]
