# Generated by Django 4.2.3 on 2023-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0006_rename_employee_uut_employee_e_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='uut',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
