# Generated by Django 4.2.3 on 2023-08-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0008_alter_booms_product_alter_booms_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stationProject',
            field=models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW')], max_length=50),
        ),
    ]
