# Generated by Django 4.2.3 on 2023-07-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0008_booms_alter_uut_pn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booms',
            old_name='ubi_logic',
            new_name='ubiLogic',
        ),
        migrations.RenameField(
            model_name='employes',
            old_name='employee_name',
            new_name='employeeName',
        ),
        migrations.RenameField(
            model_name='employes',
            old_name='employee_number',
            new_name='employeeNumber',
        ),
        migrations.RenameField(
            model_name='failures',
            old_name='corrective_actions',
            new_name='correctiveActions',
        ),
        migrations.RenameField(
            model_name='failures',
            old_name='defect_symptom',
            new_name='defectSymptom',
        ),
        migrations.RenameField(
            model_name='failures',
            old_name='error_message',
            new_name='errorMessage',
        ),
        migrations.RenameField(
            model_name='failures',
            old_name='failure_date',
            new_name='failureDate',
        ),
        migrations.RenameField(
            model_name='failures',
            old_name='root_cause',
            new_name='rootCause',
        ),
        migrations.RenameField(
            model_name='failures',
            old_name='shift_failure',
            new_name='shiftFailure',
        ),
        migrations.RenameField(
            model_name='uut',
            old_name='pn',
            new_name='pn_b',
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRejected', models.DateTimeField(auto_now=True)),
                ('snDamaged', models.CharField(max_length=50)),
                ('snNew', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=15)),
                ('employee_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.employes')),
                ('id_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.failures')),
                ('pn_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.booms')),
            ],
        ),
    ]
