# Generated by Django 4.2.3 on 2023-07-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0009_rename_ubi_logic_booms_ubilogic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('employee_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.employes')),
                ('pn_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.booms')),
            ],
        ),
    ]
