# Generated by Django 4.2.3 on 2023-08-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0009_alter_station_stationproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessages',
            name='employee_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='uut',
            name='employee_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
    ]
