# Generated by Django 4.2.3 on 2023-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0010_errormessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationProject', models.CharField(max_length=100)),
                ('stationName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('last_maintenance', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
