# Generated by Django 4.2.3 on 2023-08-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0010_alter_errormessages_employee_e_alter_uut_employee_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='shiftFailure',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=13),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='employee_e',
            field=models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
    ]
