# Generated by Django 4.2.3 on 2023-07-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0011_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='last_maintenance',
            new_name='date',
        ),
    ]
