# Generated by Django 4.2.3 on 2023-07-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0012_rename_last_maintenance_station_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceType', models.CharField(max_length=100)),
                ('failureM', models.CharField(max_length=100)),
                ('causeCategoryS', models.CharField(max_length=100)),
                ('dateStart', models.DateTimeField(auto_now=True)),
                ('dateFinish', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('employee_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.employes')),
                ('statition_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.station')),
            ],
        ),
    ]
