# Generated by Django 4.2.3 on 2023-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0012_failures_imgevindence'),
    ]

    operations = [
        migrations.AddField(
            model_name='failures',
            name='log',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
