# Generated by Django 4.2.3 on 2023-08-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0013_failures_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='imgEvindence',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='log',
            field=models.FileField(null=True, upload_to='logs/'),
        ),
    ]
