# Generated by Django 4.2.3 on 2023-07-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0013_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('pn', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='failures',
            name='errorMessage',
        ),
        migrations.AddField(
            model_name='failures',
            name='id_er',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.errormessages'),
        ),
        migrations.AddField(
            model_name='failures',
            name='id_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.station'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='id_sp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.sparepart'),
        ),
    ]
