# Generated by Django 4.2.3 on 2023-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0014_sparepart_remove_failures_errormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AddField(
            model_name='station',
            name='idStation',
            field=models.AutoField( primary_key=True, serialize=False),
        ),
    ]
