# Generated by Django 4.2.3 on 2023-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0014_alter_failures_imgevindence_alter_failures_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='imgEvindence',
            field=models.ImageField(null=True, upload_to='evindences/'),
        ),
    ]
