# Generated by Django 4.2.3 on 2023-07-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0015_alter_failures_id_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='employee_e',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='id_er',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms_db.errormessages'),
        ),
    ]
