# Generated by Django 4.2.3 on 2023-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0015_remove_station_id_station_idstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='idStation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
