# Generated by Django 4.2.3 on 2023-07-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0016_alter_failures_employee_e_alter_failures_id_er'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='employee_e',
            field=models.ForeignKey(on_delete=models.SET(1), to='forms_db.employes'),
        ),
    ]
