# Generated by Django 4.2.3 on 2023-12-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0016_alter_failures_imgevindence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='sony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booms',
            name='product',
            field=models.CharField(choices=[('Senna', 'Senna'), ('Pathfinder', 'Pathfinder'), ('Sojouner', 'Sojouner'), ('Hook', 'Hook'), ('Outlander', 'Outlander'), ('Minerrall Well', 'Minerrall Well'), ('MMCs', 'MCCs'), ('Fornax SAM', 'Fornax SAM'), ('Fornax DIB', 'Fornax DIB'), ('Fornax CIT', 'Fornax CIT'), ('Indus DIB', 'Indus DIB'), ('Indus BOP', 'Indus BOP'), ('Indus SAM', 'Indus SAM'), ('Indus CIT', 'Indus CIT'), ('PMDU', 'PMDU'), ('Switch', 'Switch'), ('Kura', 'Kura'), ('Sled', 'Sled'), ('Rack', 'Rack')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booms',
            name='project',
            field=models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW'), ('SONY', 'SONY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='failures',
            name='correctiveActions',
            field=models.CharField(choices=[('Resettled subassy and slaves parts', 'Resettled subassy and slaves parts'), ('Retest in another tester', 'Retest in another tester'), ('Retest no touch', 'Retest no touch'), ('Change component', 'Change component'), ('Clean component', 'Clean component')], max_length=100),
        ),
        migrations.AlterField(
            model_name='failures',
            name='imgEvindence',
            field=models.ImageField(blank=True, null=True, upload_to='evidences/'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='logs/'),
        ),
        migrations.AlterField(
            model_name='station',
            name='stationProject',
            field=models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW'), ('SONY', 'SONY')], max_length=50),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('serial', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nicho', models.CharField(choices=[('AB19_P01', 'AB19_P01'), ('AB19_P02', 'AB19_P02'), ('AB19_P03', 'AB19_P03'), ('AB19_P04', 'AB19_P04'), ('AB19_P06', 'AB19_P06'), ('AB19_P08', 'AB19_P08'), ('AB19_P09', 'AB19_P09'), ('AB19_P10', 'AB19_P10'), ('AB19_P11', 'AB19_P11'), ('AB19_P12', 'AB19_P12'), ('AB20_P01', 'AB20_P01'), ('AB20_P02', 'AB20_P02'), ('AB20_P03', 'AB20_P03'), ('AB20_P04', 'AB20_P04'), ('AB20_P06', 'AB20_P06'), ('AB20_P08', 'AB20_P08'), ('AB20_P09', 'AB20_P09'), ('AB20_P10', 'AB20_P10'), ('AB20_P11', 'AB20_P11'), ('AB20_P12', 'AB20_P12')], max_length=10)),
                ('shift', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('cims', models.ImageField(null=True, upload_to='media/')),
                ('crabber', models.ImageField(null=True, upload_to='media/')),
                ('employee_e', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
            ],
        ),
    ]
