# Generated by Django 4.2.3 on 2023-07-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0016_alter_station_idstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='statition_s',
        ),
        migrations.RemoveField(
            model_name='station',
            name='idStation',
        ),
        migrations.AddField(
            model_name='failures',
            name='id_er',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.errormessages'),
        ),
        migrations.AddField(
            model_name='failures',
            name='id_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.station'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='id_sp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.sparepart'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='station_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.station'),
        ),
        migrations.AddField(
            model_name='station',
            name='id',
            field=models.AutoField( primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='failures',
            name='sn_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.uut'),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='id_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.failures'),
        ),
    ]
