# Generated by Django 4.2.2 on 2023-12-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0017_employes_sony_alter_booms_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='statition_s',
            new_name='station_s',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='causeCategoryS',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='failureM',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenanceType',
            field=models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective')], max_length=100),
        ),
    ]
