# Generated by Django 4.2.3 on 2023-07-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0017_alter_failures_employee_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='id_er',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.errormessages'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='id_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.station'),
        ),
    ]
