# Generated by Django 4.2.3 on 2023-07-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0018_alter_failures_id_er_alter_failures_id_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uut',
            name='employee_e',
            field=models.ForeignKey(on_delete=models.SET('Ex employee'), to='forms_db.employes'),
        ),
    ]
