# Generated by Django 4.2.2 on 2023-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0018_rename_statition_s_maintenance_station_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
