# Generated by Django 4.2.3 on 2023-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0019_alter_uut_employee_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessages',
            name='employee_e',
            field=models.ForeignKey(on_delete=models.SET('Ex employee'), to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='employee_e',
            field=models.ForeignKey(on_delete=models.SET('Ex employee'), to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='employee_e',
            field=models.ForeignKey(on_delete=models.SET('Ex employee'), to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='employee_e',
            field=models.ForeignKey(on_delete=models.SET('Ex employee'), to='forms_db.employes'),
        ),
    ]
