# Generated by Django 4.2.2 on 2024-02-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0020_alter_maintenance_datestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='correctiveActions',
            field=models.CharField(choices=[('Resettled subassy and slaves parts', 'Resettled subassy and slaves parts'), ('Retest in another tester', 'Retest in another tester'), ('Retest no touch', 'Retest no touch'), ('Change component', 'Change component'), ('Clean component', 'Clean component'), ('reset equipment and retest', 'reset equipment and retest')], max_length=100),
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('employee_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.station')),
                ('uut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.uut')),
            ],
        ),
    ]
