# Generated by Django 4.2.3 on 2023-07-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0020_alter_errormessages_employee_e_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessages',
            name='employee_e',
            field=models.ForeignKey(default='ex', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='employee_e',
            field=models.ForeignKey(default='ex', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='employee_e',
            field=models.ForeignKey(default='ex', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='employee_e',
            field=models.ForeignKey(default='ex', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='uut',
            name='employee_e',
            field=models.ForeignKey(default='ex', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms_db.employes'),
        ),
    ]
