# Generated by Django 4.2.3 on 2023-07-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0020_alter_station_idi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failures',
            name='id_s',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='id_sp',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='station_s',
        ),
        migrations.RemoveField(
            model_name='rejected',
            name='id_f',
        ),
    ]
