# Generated by Django 4.2.3 on 2023-07-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0021_remove_failures_id_s_remove_maintenance_id_sp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failures',
            name='id_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.station'),
        ),
    ]
