# Generated by Django 4.2.3 on 2023-07-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0022_failures_id_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejected',
            name='id_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.failures'),
        ),
    ]
