# Generated by Django 4.2.3 on 2023-07-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0023_rejected_id_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='id_sp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.sparepart'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='station_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_db.station'),
        ),
    ]
