# Generated by Django 4.2.3 on 2023-07-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0023_alter_errormessages_employee_e_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='employee_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='id_er',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.errormessages'),
        ),
        migrations.AlterField(
            model_name='failures',
            name='id_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.station'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='id_sp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.sparepart'),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='pn_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.booms'),
        ),
        migrations.AlterField(
            model_name='uut',
            name='pn_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.booms'),
        ),
    ]
